Albert/login logout
GrinnellAppDev/DB-Android pull request #3
Opened 2017-02-23 05:17 UTC by as-f

* User class now is better documented and has full functionality
* When you click the Sign In button in Login Activity, an event handler gets the username and password and does nothing with them yet

2017-02-23 06:29 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/appdev/grinnelldirectory/LoginActivity.java
> +    @BindView(R.id.username) EditText username;
you should use access modifiers here. Also, please remember to use our conventional variable naming. eg. This should read: 
`@BindView(R.id.username) private EditText mUsernameEditText`; or ``@BindView(R.id.username) private EditText mUsername`;

In the end, we want anyone who sees this variable called anywhere to know that it is a member variable (hence the "m" prefix) and should you choose to call it `mUsernameEditText` it also makes us know what it really is (an EditText which is a member variable)

2017-02-23 06:31 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/appdev/grinnelldirectory/LoginActivity.java
> +    public void signin(View view) {
Will this method be called anywhere outside this activity? I doubt that. If it isn't, this should be marked `private`. Also use camel case here as such: `public void signIn(View view)`

2017-02-23 06:32 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/appdev/grinnelldirectory/User.java
>      public static void saveCredentials(Context context, String username, String password) {
Just to be on the safe side here, I'd just check to make sure `username` and `password` are not null or empty. Exit the function immediately if either or both are.

2017-02-23 06:33 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/appdev/grinnelldirectory/LoginActivity.java
You've done some very good documentation in your methods and it'll be nice to extend that here too! Let's document this class :)

2017-02-23 06:34 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/appdev/grinnelldirectory/User.java
> + * The User class represents the user of the app.
I really like this documentation! Good job here, @as-f !

2017-02-23 06:35 UTC, LarryAsante requested changes
Albert, this looks *very* good. A few changes and we'll be there! Please see my comments. I really like the work being done here and I hope others can look at this as well!

2017-02-25 13:57 UTC, as-f commented
I made the changes @LarryAsante

2017-02-25 17:56 UTC, LarryAsante approved these changes

2017-02-25 17:57 UTC, merged