Nazarovo/advanced search
GrinnellAppDev/DB-Android pull request #7
Opened 2017-03-05 20:04 UTC by mudabek

2017-03-10 05:01 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/appdev/grinnelldirectory/Activity/AdvancedSearchActivity.java
> +
Add proper documentation to this class

2017-03-10 05:02 UTC, LarryAsante commented on app/src/main/java/edu/grinnell/appdev/grinnelldirectory/Activity/AdvancedSearchActivity.java
> +
If you write your own methods and make them public, you should document them

2017-03-10 05:03 UTC, LarryAsante requested changes
Check the comments -- some slight additions and we should be good to go

2017-03-10 08:55 UTC, prabirmsp requested changes

2017-03-10 08:55 UTC, prabirmsp commented on app/src/main/java/edu/grinnell/appdev/grinnelldirectory/Activity/AdvancedSearchActivity.java
> +
@mudabek check out @as-f 's branches - he has excellent documentation

2017-03-10 08:55 UTC, prabirmsp commented on app/src/main/res/values/strings.xml
> +
@LarryAsante is it better to put these in here, in a `Constants.java` file, or put it on a server and pull it to make it easier to change?

2017-03-10 08:55 UTC, prabirmsp commented on app/src/main/res/values/styles.xml
> +    <style name="AppTheme" parent="Base.Theme.AppCompat">
@mudabek no need to change the theme yet...

2017-04-07 00:04 UTC, prabirmsp commented
@mudabek make the changes and push

2017-05-05 18:32 UTC, closed without merging