albert/simple-search
GrinnellAppDev/DB-Android pull request #8
Opened 2017-04-09 18:52 UTC by as-f

Implement the network method callbacks, and put the list of persons into a parcelable to pass it through an intent.

2017-04-09 19:43 UTC, mattorib requested changes

2017-04-09 19:43 UTC, PsychicNoodles commented on app/src/main/java/edu/grinnell/appdev/grinnelldirectory/activities/SimpleSearchActivity.java
> +    public static final String BUNDLE_KEY = "BUNDLE_KEY";
This should be unique to the `SimpleSearchActivity` in case someone else wants to have a bundle key.

2017-04-09 19:43 UTC, PsychicNoodles commented on app/src/main/java/edu/grinnell/appdev/grinnelldirectory/activities/SimpleSearchActivity.java
> +    @Override public void authenticateUserCallSuccess(boolean success, Person person) {
@as-f Is this intentionally blank? It might be worth adding a comment so people don't get confused, since there isn't any code here.

2017-04-09 19:43 UTC, PsychicNoodles commented on app/src/main/java/edu/grinnell/appdev/grinnelldirectory/activities/SimpleSearchActivity.java
> +    @Override public void onServerFailure(String fail_message) {
Variable naming in Java follows `camelCase` rather than `under_scores`, so please change the variable name.

2017-04-09 19:43 UTC, PsychicNoodles commented on app/src/main/java/edu/grinnell/appdev/grinnelldirectory/activities/SimpleSearchActivity.java
> +    @Override public void onNetworkingError(String fail_message) {
See above.

2017-04-09 19:43 UTC, PsychicNoodles commented on app/src/main/java/edu/grinnell/appdev/grinnelldirectory/models/SimpleResult.java
> +    List<Person> people;
Change this to follow the `m` + variable name convention for fields.

2017-04-10 16:32 UTC, prabirmsp requested changes

2017-04-10 16:32 UTC, prabirmsp commented on app/src/main/java/edu/grinnell/appdev/grinnelldirectory/models/SimpleResult.java
> +public class SimpleResult implements Parcelable {
This is a class that should be tested before using! Could you please write an androidTest class for this that tests all parts of this class that we will be using? For example, create a list of random `Person`s, and check if it parcels it without error. Then recreate the list (un-parcel), and compare that object to the original list @as-f

2017-04-10 16:32 UTC, prabirmsp commented on app/src/main/java/edu/grinnell/appdev/grinnelldirectory/models/SimpleResult.java
> +    static Parcelable.Creator CREATOR = new Parcelable.Creator<SimpleResult>() {
Could you explain what's happening here, and when this creator is used? Additionally, comments would also be helpful

2017-04-16 19:38 UTC, as-f commented
The test is written and it passes.  
You can search for people, and the search results page displays the results correctly.

2017-04-16 19:47 UTC, prabirmsp approved these changes

2017-04-16 19:47 UTC, merged